import { ENTRY_COIN_PRICE, WIN_REWARD_COINS, PEEK_COIN_PRICE_BASE, ALLOW_TEST_NICKNAME } from "./runtime-config.js";

export const COIN_PRICE = ENTRY_COIN_PRICE;
export const WIN_REWARD = WIN_REWARD_COINS;
export const PEEK_PRICE_BASE = PEEK_COIN_PRICE_BASE;
export { ALLOW_TEST_NICKNAME };
export const PAYMENT_POLL_MS = 1500;
